"""Add missing tables

Revision ID: 445ec7b0c9a4
Revises: ca3d41bc35a1
Create Date: 2026-01-29 01:02:46.856185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '445ec7b0c9a4'
down_revision: Union[str, Sequence[str], None] = 'ca3d41bc35a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
