"""Add chat tables

Revision ID: 9520986c8004
Revises: a21f3ebec1e8
Create Date: 2026-01-29 00:50:51.963490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9520986c8004'
down_revision: Union[str, Sequence[str], None] = 'a21f3ebec1e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.drop_table('resumes')
    op.drop_table('job_applications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_applications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('company_name', sa.VARCHAR(), nullable=False),
    sa.Column('job_title', sa.VARCHAR(), nullable=False),
    sa.Column('application_date', sa.DATETIME(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resumes',
    sa.Column('resume_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('uploaded_by_user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('candidate_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_path', sa.TEXT(), nullable=False),
    sa.Column('vector_index_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_indexed', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('resume_id')
    )
    op.create_table('jobs',
    sa.Column('job_id', sa.TEXT(), nullable=True),
    sa.Column('created_by_user_id', sa.TEXT(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('requirements', sa.TEXT(), nullable=True),
    sa.Column('location', sa.TEXT(), nullable=False),
    sa.Column('salary', sa.TEXT(), nullable=True),
    sa.Column('type', sa.TEXT(), server_default=sa.text("'full-time'"), nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###
