"""Add current_session_id to users table

Revision ID: c45f551bb843
Revises: 6c40f3e67475
Create Date: 2026-01-29 01:11:49.335471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c45f551bb843'
down_revision: Union[str, Sequence[str], None] = '6c40f3e67475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_session_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_session_id')
    # ### end Alembic commands ###
